const PDFDocument = require('pdfkit');

/**
 * Generates a styled PDF report for a citizen's complaint and AI legal analysis
 * @param {Object} complaint - The Mongoose complaint document populated with user details
 * @param {Object} res - Express response stream
 */
const generateComplaintPDF = (complaint, res) => {
  const doc = new PDFDocument({
    size: 'A4',
    margins: { top: 50, bottom: 60, left: 50, right: 50 }
  });

  // Pipe the PDF directly to the client response
  doc.pipe(res);

  // Styling Constants
  const PRIMARY_COLOR = '#1e3a8a';   // Navy Blue
  const SECONDARY_COLOR = '#475569'; // Slate Gray
  const TEXT_COLOR = '#1f2937';      // Dark Charcoal
  const WARNING_BG = '#fffbeb';      // Amber 50
  const WARNING_BORDER = '#d97706';  // Amber 600
  const LIGHT_BORDER = '#e2e8f0';    // Slate 200

  // Register Footer callback for all pages
  let pageNumber = 0;
  doc.on('pageAdded', () => {
    pageNumber++;
    const oldBottom = doc.page.margins.bottom;
    doc.page.margins.bottom = 0;
    
    // Draw running header/footer
    doc.fillColor(SECONDARY_COLOR)
       .fontSize(8)
       .text(
         'LegalAssist - AI-Powered Citizen Legal Guidance System', 
         50, 
         doc.page.height - 45, 
         { align: 'left', width: 300 }
       );

    doc.text(
      `Page ${pageNumber}`, 
      doc.page.width - 150, 
      doc.page.height - 45, 
      { align: 'right', width: 100 }
    );
    
    doc.text(
      'Disclaimer: Informational guidance only. Not a substitute for professional legal advice.',
      50,
      doc.page.height - 30,
      { align: 'center', width: doc.page.width - 100 }
    );
    
    doc.page.margins.bottom = oldBottom;
  });

  // Manually trigger page number for the first page
  pageNumber = 1;

  // Header Logo and Title
  doc.fillColor(PRIMARY_COLOR)
     .fontSize(22)
     .font('Helvetica-Bold')
     .text('LegalAssist', 50, 45);

  doc.fillColor(SECONDARY_COLOR)
     .fontSize(10)
     .font('Helvetica')
     .text('AI-Powered Citizen Legal Guidance Report', 50, 70);

  // Horizontal Rule
  doc.moveTo(50, 85)
     .lineTo(doc.page.width - 50, 85)
     .strokeColor(LIGHT_BORDER)
     .lineWidth(1)
     .stroke();

  // Draw Prominent Disclaimer Box
  const disclaimerText = "IMPORTANT DISCLAIMER: This platform provides informational guidance only and is not a substitute for professional legal advice, court proceedings, or official judicial decisions. The content below is generated by AI for educational purposes to help prepare you for consultation with a licensed advocate.";
  
  doc.rect(50, 100, doc.page.width - 100, 50)
     .fillAndStroke(WARNING_BG, WARNING_BORDER);

  doc.fillColor('#92400e')
     .fontSize(8.5)
     .font('Helvetica-Bold')
     .text('LEGAL NOTICE & LIMITATION OF LIABILITY:', 60, 106);

  doc.fillColor('#b45309')
     .font('Helvetica')
     .fontSize(8)
     .text(disclaimerText, 60, 118, { width: doc.page.width - 120, lineGap: 2 });

  // Incident & User Info Metadata Grid
  doc.y = 165;
  const metadataY = doc.y;

  doc.fillColor(PRIMARY_COLOR).font('Helvetica-Bold').fontSize(11).text('CASE DETAILS', 50, metadataY);
  doc.fillColor(TEXT_COLOR).font('Helvetica-Bold').fontSize(9).text('Complaint ID: ', 50, metadataY + 20);
  doc.font('Helvetica').text(complaint._id.toString(), 130, metadataY + 20);

  doc.font('Helvetica-Bold').text('Title: ', 50, metadataY + 35);
  doc.font('Helvetica').text(complaint.title, 130, metadataY + 35, { width: 180 });

  doc.font('Helvetica-Bold').text('Incident Date: ', 50, metadataY + 65);
  doc.font('Helvetica').text(new Date(complaint.incidentDate).toLocaleDateString(), 130, metadataY + 65);

  // Column 2 (Right side)
  const col2X = 350;
  doc.fillColor(PRIMARY_COLOR).font('Helvetica-Bold').fontSize(11).text('CITIZEN INFO', col2X, metadataY);
  doc.fillColor(TEXT_COLOR).font('Helvetica-Bold').fontSize(9).text('Submitted By: ', col2X, metadataY + 20);
  doc.font('Helvetica').text(complaint.citizen?.username || 'Citizen User', col2X + 80, metadataY + 20);

  doc.font('Helvetica-Bold').text('Location: ', col2X, metadataY + 35);
  doc.font('Helvetica').text(`${complaint.district}, ${complaint.state}`, col2X + 80, metadataY + 35);

  doc.font('Helvetica-Bold').text('Status: ', col2X, metadataY + 50);
  doc.font('Helvetica-Bold').fillColor(complaint.status === 'resolved' ? '#16a34a' : '#ea580c').text(complaint.status.toUpperCase(), col2X + 80, metadataY + 50);

  doc.y = metadataY + 90;
  doc.moveTo(50, doc.y)
     .lineTo(doc.page.width - 50, doc.y)
     .strokeColor(LIGHT_BORDER)
     .stroke();

  // AI Response Content (if available)
  const ai = complaint.aiResponse;
  if (ai) {
    // 1. Summary
    doc.y += 15;
    doc.fillColor(PRIMARY_COLOR).font('Helvetica-Bold').fontSize(12).text('1. Executive Grievance Summary', 50, doc.y);
    doc.fillColor(TEXT_COLOR).font('Helvetica').fontSize(9.5).text(ai.summary, 50, doc.y + 18, { width: doc.page.width - 100, lineGap: 3 });

    // 2. Classification
    doc.y = doc.y + doc.heightOfString(ai.summary, { width: doc.page.width - 100 }) + 30;
    doc.fillColor(PRIMARY_COLOR).font('Helvetica-Bold').fontSize(12).text('2. Legal Classification & Jurisdiction', 50, doc.y);
    
    doc.fillColor(TEXT_COLOR).font('Helvetica-Bold').fontSize(9.5).text('Subject Area: ', 50, doc.y + 18);
    doc.font('Helvetica').text(ai.classification, 150, doc.y + 18);

    doc.fillColor(TEXT_COLOR).font('Helvetica-Bold').text('Suggested Forum: ', 50, doc.y + 33);
    doc.font('Helvetica').text(ai.suggestedAuthority, 150, doc.y + 33, { width: doc.page.width - 200 });

    // 3. Applicable Laws
    doc.y = doc.y + 55;
    doc.fillColor(PRIMARY_COLOR).font('Helvetica-Bold').fontSize(12).text('3. Potential Applicable Laws (Informational)', 50, doc.y);
    doc.y += 18;

    ai.applicableLaws.forEach((item, index) => {
      doc.fillColor(TEXT_COLOR).font('Helvetica-Bold').fontSize(9.5).text(`${index + 1}. ${item.law}`, 55, doc.y);
      doc.font('Helvetica').fontSize(9).text(item.description, 70, doc.y + 13, { width: doc.page.width - 120, lineGap: 2 });
      doc.y += doc.heightOfString(item.description, { width: doc.page.width - 120 }) + 22;
    });

    // Page Break for procedure/docs if height is large
    if (doc.y > doc.page.height - 180) {
      doc.addPage();
      doc.y = 50;
    }

    // 4. Required Evidence & Documents
    doc.fillColor(PRIMARY_COLOR).font('Helvetica-Bold').fontSize(12).text('4. Recommended Supporting Documents & Evidence', 50, doc.y);
    doc.y += 18;
    ai.requiredDocuments.forEach((docu) => {
      doc.fillColor(TEXT_COLOR).font('Helvetica').fontSize(9).text(`[  ]  ${docu}`, 65, doc.y);
      doc.y += 16;
    });

    // 5. Step-by-Step Procedure
    doc.y += 15;
    if (doc.y > doc.page.height - 150) {
      doc.addPage();
      doc.y = 50;
    }
    doc.fillColor(PRIMARY_COLOR).font('Helvetica-Bold').fontSize(12).text('5. Step-by-Step Resolution Procedure', 50, doc.y);
    doc.y += 18;
    ai.stepByStepProcedure.forEach((step, index) => {
      doc.fillColor(PRIMARY_COLOR).font('Helvetica-Bold').fontSize(9.5).text(`${index + 1}`, 55, doc.y);
      doc.fillColor(TEXT_COLOR).font('Helvetica').fontSize(9).text(step, 70, doc.y, { width: doc.page.width - 120, lineGap: 2 });
      doc.y += doc.heightOfString(step, { width: doc.page.width - 120 }) + 10;
    });

    // 6. Next Actions & Preventive Tips
    if (doc.y > doc.page.height - 180) {
      doc.addPage();
      doc.y = 50;
    }
    doc.y += 15;
    doc.fillColor(PRIMARY_COLOR).font('Helvetica-Bold').fontSize(12).text('6. Recommended Next Steps', 50, doc.y);
    doc.y += 18;
    ai.nextActions.forEach((action) => {
      doc.fillColor(TEXT_COLOR).font('Helvetica').fontSize(9).text(`•  ${action}`, 65, doc.y, { width: doc.page.width - 120, lineGap: 2 });
      doc.y += doc.heightOfString(action, { width: doc.page.width - 120 }) + 8;
    });

    doc.y += 10;
    doc.fillColor(PRIMARY_COLOR).font('Helvetica-Bold').fontSize(11).text('Preventive Tips to Safeguard Rights:', 50, doc.y);
    doc.y += 18;
    ai.preventiveTips.forEach((tip) => {
      doc.fillColor(TEXT_COLOR).font('Helvetica').fontSize(9).text(`-  ${tip}`, 65, doc.y, { width: doc.page.width - 120, lineGap: 2 });
      doc.y += doc.heightOfString(tip, { width: doc.page.width - 120 }) + 8;
    });

    // 7. Frequently Asked Questions
    if (doc.y > doc.page.height - 180) {
      doc.addPage();
      doc.y = 50;
    }
    doc.y += 20;
    doc.fillColor(PRIMARY_COLOR).font('Helvetica-Bold').fontSize(12).text('7. Frequently Asked Questions', 50, doc.y);
    doc.y += 18;
    ai.faqs.forEach((faq) => {
      doc.fillColor(TEXT_COLOR).font('Helvetica-Bold').fontSize(9.5).text(`Q: ${faq.question}`, 55, doc.y, { width: doc.page.width - 100 });
      doc.y += doc.heightOfString(`Q: ${faq.question}`, { width: doc.page.width - 100 }) + 4;
      doc.fillColor(TEXT_COLOR).font('Helvetica').fontSize(9).text(`A: ${faq.answer}`, 55, doc.y, { width: doc.page.width - 100, lineGap: 2 });
      doc.y += doc.heightOfString(`A: ${faq.answer}`, { width: doc.page.width - 100 }) + 14;
    });
  } else {
    doc.y += 30;
    doc.fillColor(SECONDARY_COLOR).font('Helvetica-Oblique').fontSize(12).text('AI legal analysis report is still pending for this complaint. Please wait for processing.', 50, doc.y, { align: 'center' });
  }

  // End of Document
  doc.end();
};

module.exports = {
  generateComplaintPDF
};
